import { create } from "zustand";

// Available handlers for random assignment
const handlers = ['Lily Anderson', 'Emma Thompson', 'Sarah Johnson', 'Michael Chen'];

// Placeholder images provided
const productImages = [
  '/colorful-flower-bouquet-with-roses-and-daisies.jpg',
  '/large-vibrant-flower-arrangement-with-mixed-blooms.jpg',
  '/orange-yellow-flowers-bouquet.jpg',
  '/pink-purple-flowers-bouquet.jpg',
  '/bouquet_square_1.jpeg',
  '/bouquet_square_2.jpeg',
  '/bouquet_square_3.jpeg',
  '/bouquet_square_4.jpeg',
  '/bouquet_square_5.jpeg',
  '/bouquet_square_6.jpeg',
  '/bouquet_square_7.jpeg',
  '/bouquet_square_8.jpeg',
  '/bouquet_square_9.jpeg',
  '/bouquet_square_10.jpeg',
  '/bouquet_square_11.jpeg'
];

const initialOrders = [
  { 
    _id: '1112233', 
    customerName: 'Steven Grant Rogers', 
    recipientEmail: 'steve.rogers@aol.com',
    recipientPhone: '678-136-7092',
    recipientName: 'Margaret Elizabeth Carter',
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-25T21:24:51'), 
    priority: 'rush', 
    status: 'pending', 
    handler: 'Lily Anderson',
    deliveryDate: new Date('2025-07-26T09:00:00'), 
    addressLine1: 'Carter Residence, Columbia Heights, Washington, D.C.', 
    specialMessage: 'Hello, Peggy! I hope you like these flowers.', 
    paymentMethod: 'PayPal', 
    totalAmount: 100.00,
    items: [{ name: 'Patriotic Blooms', price: 100.00, quantity: 1, image: '/bouquet_square_1.jpeg' }] 
  },
  { 
    _id: '1112234', 
    customerName: 'Tony Stark', 
    recipientEmail: 'tony.stark@starkindustries.com',
    recipientPhone: '555-0101',
    recipientName: 'Pepper Potts',
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-25T21:25:30'), 
    priority: 'Normal', 
    status: 'pending', 
    handler: 'Emma Thompson',
    deliveryDate: new Date('2025-07-27T14:00:00'), 
    addressLine1: '10880 Malibu Point, Malibu, CA 90265', 
    specialMessage: 'Happy Anniversary! I built these myself (not really).', 
    paymentMethod: 'Credit Card', 
    totalAmount: 55.00,
    items: [{ name: 'Iron Red Roses', price: 55.00, quantity: 1, image: '/bouquet_square_2.jpeg' }]
  },
  { 
    _id: '1112235', 
    customerName: 'Natasha Romanoff', 
    recipientEmail: 'natasha.r@gmail.com',
    recipientPhone: '555-0102',
    recipientName: 'Clint Barton',
    deliveryType: 'Facebook', 
    createdAt: new Date('2025-07-25T10:15:22'), 
    priority: 'same-day', 
    status: 'completed', 
    handler: 'Sarah Johnson',
    deliveryDate: new Date('2025-07-25T16:00:00'), 
    addressLine1: '123 Hawkeye Lane, Iowa City, IA', 
    specialMessage: 'Thanks for being a great friend! Budapest was fun.', 
    paymentMethod: 'PayPal', 
    totalAmount: 65.00,
    items: [{ name: 'Black Dahlia Mix', price: 65.00, quantity: 1, image: '/bouquet_square_3.jpeg' }]
  },
  { 
    _id: '1133544', 
    customerName: 'Thor Odinson', 
    recipientEmail: 'thor@asgard.com',
    recipientPhone: '555-0104',
    recipientName: 'Jane Foster',
    deliveryType: 'Phone Call', 
    createdAt: new Date('2025-07-24T08:20:10'), 
    priority: 'rush', 
    status: 'completed', 
    handler: 'Michael Chen',
    deliveryDate: new Date('2025-07-24T10:00:00'), 
    addressLine1: '456 Asgard Avenue, Norway', 
    specialMessage: 'ANOTHER! (Bouquet)', 
    paymentMethod: 'Cash', 
    totalAmount: 92.00,
    items: [{ name: 'Thunder Lilies', price: 92.00, quantity: 1, image: '/bouquet_square_4.jpeg' }]
  },
  { 
    _id: '1133545', 
    customerName: 'Bruce Banner', 
    recipientEmail: 'bruce.banner@avengers.com', 
    recipientPhone: '555-0105', 
    recipientName: 'Betty Ross', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-23T14:15:00'), 
    priority: 'Normal', 
    status: 'pending', 
    handler: 'Lily Anderson',
    deliveryDate: new Date('2025-07-25T10:00:00'), 
    addressLine1: 'Culver University, Willowdale, VA', 
    specialMessage: 'Thinking of you. Don\'t make me angry.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 45.50, 
    items: [{ name: 'Green Hydrangeas', price: 45.50, quantity: 1, image: '/bouquet_square_5.jpeg' }] 
  },
  { 
    _id: '1133546', 
    customerName: 'Peter Parker', 
    recipientEmail: 'spidey@queens.ny', 
    recipientPhone: '555-0106', 
    recipientName: 'Mary Jane Watson', 
    deliveryType: 'In-Store', 
    createdAt: new Date('2025-07-23T09:30:00'), 
    priority: 'same-day', 
    status: 'completed', 
    handler: 'Emma Thompson',
    deliveryDate: new Date('2025-07-23T17:00:00'), 
    addressLine1: '20 Ingram Street, Queens, NY', 
    specialMessage: 'Face it Tiger, you just hit the jackpot!', 
    paymentMethod: 'Cash', 
    totalAmount: 35.00, 
    items: [{ name: 'Webbed White Roses', price: 35.00, quantity: 1, image: '/bouquet_square_6.jpeg' }] 
  },
  { 
    _id: '1133547', 
    customerName: 'Wanda Maximoff', 
    recipientEmail: 'wanda@westview.nj', 
    recipientPhone: '555-0107', 
    recipientName: 'Vision', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-22T16:45:00'), 
    priority: 'rush', 
    status: 'cancelled', 
    handler: 'Sarah Johnson',
    deliveryDate: new Date('2025-07-23T09:00:00'), 
    addressLine1: '2800 Sherwood Drive, Westview, NJ', 
    specialMessage: 'To my darling Vision.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 120.00, 
    items: [{ name: 'Chaos Magic Tulips', price: 120.00, quantity: 1, image: '/bouquet_square_7.jpeg' }] 
  },
  { 
    _id: '1133548', 
    customerName: 'Stephen Strange', 
    recipientEmail: 'doctor@sanctum.ny', 
    recipientPhone: '555-0108', 
    recipientName: 'Christine Palmer', 
    deliveryType: 'Phone Call', 
    createdAt: new Date('2025-07-22T11:20:00'), 
    priority: 'Normal', 
    status: 'pending', 
    handler: 'Michael Chen',
    deliveryDate: new Date('2025-07-24T12:00:00'), 
    addressLine1: 'Metro-General Hospital, NY', 
    specialMessage: 'I have come to bargain.', 
    paymentMethod: 'PayPal', 
    totalAmount: 85.00, 
    items: [{ name: 'Mystic Orchids', price: 85.00, quantity: 1, image: '/bouquet_square_8.jpeg' }] 
  },
  { 
    _id: '1133549', 
    customerName: 'T\'Challa', 
    recipientEmail: 'king@wakanda.gov', 
    recipientPhone: '555-0109', 
    recipientName: 'Nakia', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-21T08:00:00'), 
    priority: 'rush', 
    status: 'completed', 
    handler: 'Lily Anderson',
    deliveryDate: new Date('2025-07-22T15:00:00'), 
    addressLine1: 'Royal Palace, Birnin Zana, Wakanda', 
    specialMessage: 'Wakanda Forever.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 250.00, 
    items: [{ name: 'Heart Shaped Herbs', price: 250.00, quantity: 1, image: '/bouquet_square_9.jpeg' }] 
  },
  { 
    _id: '1133550', 
    customerName: 'Scott Lang', 
    recipientEmail: 'antman@pymtech.com', 
    recipientPhone: '555-0110', 
    recipientName: 'Cassie Lang', 
    deliveryType: 'Facebook', 
    createdAt: new Date('2025-07-20T14:10:00'), 
    priority: 'Normal', 
    status: 'pending', 
    handler: 'Emma Thompson',
    deliveryDate: new Date('2025-07-23T16:00:00'), 
    addressLine1: '1404 Willow Road, San Francisco, CA', 
    specialMessage: 'Happy Birthday Peanut! Use the Pym particles responsibly.', 
    paymentMethod: 'PayPal', 
    totalAmount: 55.00, 
    items: [{ name: 'Giant Peonies', price: 55.00, quantity: 1, image: '/bouquet_square_10.jpeg' }] 
  },
  { 
    _id: '1133551', 
    customerName: 'Leopold Fitz', 
    recipientEmail: 'fitz@shield.gov', 
    recipientPhone: '555-0111', 
    recipientName: 'Gemma Simmons', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-19T19:30:00'), 
    priority: 'same-day', 
    status: 'completed', 
    handler: 'Sarah Johnson',
    deliveryDate: new Date('2025-07-20T10:00:00'), 
    addressLine1: 'SHIELD Science Division', 
    specialMessage: 'For my favorite lab partner. Science never looked so beautiful.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 75.00,
    items: [{ name: 'Scottish Bouquet', price: 75.00, quantity: 1, image: '/bouquet_square_11.jpeg' }] 
  },
  { 
    _id: '1133552', 
    customerName: 'Clint Barton', 
    recipientEmail: 'hawkeye@shield.gov', 
    recipientPhone: '555-0112', 
    recipientName: 'Laura Barton', 
    deliveryType: 'Phone Call', 
    createdAt: new Date('2025-07-18T10:05:00'), 
    priority: 'rush', 
    status: 'pending', 
    handler: 'Michael Chen',
    deliveryDate: new Date('2025-07-19T09:00:00'), 
    addressLine1: 'The Farm, Missouri', 
    specialMessage: 'Don\'t give me hope.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 95.00, 
    items: [{ name: 'Farmhouse Wildflowers', price: 95.00, quantity: 1, image: '/orange-yellow-flowers-bouquet.jpg' }] 
  },
  { 
    _id: '1133553', 
    customerName: 'Bucky Barnes', 
    recipientEmail: 'wintersoldier@unknown.loc', 
    recipientPhone: '555-0113', 
    recipientName: 'Yelena Belova', 
    deliveryType: 'In-Store', 
    createdAt: new Date('2025-07-17T13:20:00'), 
    priority: 'Normal', 
    status: 'completed', 
    handler: 'Lily Anderson',
    deliveryDate: new Date('2025-07-18T14:00:00'), 
    addressLine1: 'Safe House, Eastern Europe', 
    specialMessage: 'The Red Room can\'t keep us apart. Stay safe, comrade.', 
    paymentMethod: 'Cash', 
    totalAmount: 40.00,
    items: [{ name: 'Vibranium Violets', price: 40.00, quantity: 1, image: '/pink-purple-flowers-bouquet.jpg' }] 
  },
  { 
    _id: '1133554', 
    customerName: 'Hope Van Dyne', 
    recipientEmail: 'hope@pymtech.com', 
    recipientPhone: '555-0114', 
    recipientName: 'Hank Pym', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-16T09:15:00'), 
    priority: 'same-day', 
    status: 'pending', 
    handler: 'Emma Thompson',
    deliveryDate: new Date('2025-07-16T18:00:00'), 
    addressLine1: 'Pym Residence, San Francisco', 
    specialMessage: 'Lab supplies disguised as flowers.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 150.00, 
    items: [{ name: 'Quantum Lilacs', price: 150.00, quantity: 1, image: '/colorful-flower-bouquet-with-roses-and-daisies.jpg' }] 
  },
  { 
    _id: '1133555', 
    customerName: 'Peter Quill', 
    recipientEmail: 'starlord@gotg.space', 
    recipientPhone: '555-0115', 
    recipientName: 'Gamora', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-15T11:45:00'), 
    priority: 'Normal', 
    status: 'pending', 
    handler: 'Sarah Johnson',
    deliveryDate: new Date('2025-07-25T12:00:00'), 
    addressLine1: 'Knowhere', 
    specialMessage: 'I hooked on a feeling.', 
    paymentMethod: 'PayPal', 
    totalAmount: 88.00, 
    items: [{ name: 'Galaxy Gerberas', price: 88.00, quantity: 1, image: '/large-vibrant-flower-arrangement-with-mixed-blooms.jpg' }] 
  },
  { 
    _id: '1133556', 
    customerName: 'Nick Fury', 
    recipientEmail: 'director@shield.gov', 
    recipientPhone: '555-0116', 
    recipientName: 'Maria Hill', 
    deliveryType: 'Phone Call', 
    createdAt: new Date('2025-07-14T14:30:00'), 
    priority: 'rush', 
    status: 'active', 
    handler: 'Michael Chen',
    deliveryDate: new Date('2025-07-14T16:00:00'), 
    addressLine1: 'Helicarrier No. 64', 
    specialMessage: 'Eyes open.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 115.00, 
    items: [{ name: 'Spy Roses', price: 115.00, quantity: 1, image: '/bouquet_square_1.jpeg' }] 
  },
  { 
    _id: '1133557', 
    customerName: 'Loki Laufeyson', 
    recipientEmail: 'loki@tva.time', 
    recipientPhone: '555-0117', 
    recipientName: 'Sylvie', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-13T08:10:00'), 
    priority: 'Normal', 
    status: 'completed', 
    handler: 'Lily Anderson',
    deliveryDate: new Date('2025-07-13T12:00:00'), 
    addressLine1: 'The Void at the End of Time', 
    specialMessage: 'Glorious purpose.', 
    paymentMethod: 'PayPal', 
    totalAmount: 77.00, 
    items: [{ name: 'Timeline Tulips', price: 77.00, quantity: 1, image: '/bouquet_square_2.jpeg' }] 
  },
  { 
    _id: '1133558', 
    customerName: 'Matt Murdock', 
    recipientEmail: 'daredevil@hellskitchen.ny', 
    recipientPhone: '555-0118', 
    recipientName: 'Karen Page', 
    deliveryType: 'In-Store', 
    createdAt: new Date('2025-07-12T17:00:00'), 
    priority: 'same-day', 
    status: 'pending', 
    handler: 'Emma Thompson',
    deliveryDate: new Date('2025-07-12T19:00:00'), 
    addressLine1: 'Nelson & Murdock Law Office', 
    specialMessage: 'Justice is blind, but these flowers aren\'t.', 
    paymentMethod: 'Cash', 
    totalAmount: 60.00, 
    items: [{ name: 'Justice Jasmine', price: 60.00, quantity: 1, image: '/bouquet_square_3.jpeg' }] 
  },
  { 
    _id: '1133559', 
    customerName: 'Kamala Khan', 
    recipientEmail: 'msmarvel@jersey.nj', 
    recipientPhone: '555-0119', 
    recipientName: 'Bruno Carrelli', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-11T15:20:00'), 
    priority: 'Normal', 
    status: 'active', 
    handler: 'Sarah Johnson',
    deliveryDate: new Date('2025-07-12T14:00:00'), 
    addressLine1: 'Circle Q, Jersey City', 
    specialMessage: 'Embiggen!', 
    paymentMethod: 'PayPal', 
    totalAmount: 42.00, 
    items: [{ name: 'Marvelous Marigolds', price: 42.00, quantity: 1, image: '/bouquet_square_4.jpeg' }] 
  },
  { 
    _id: '1133560', 
    customerName: 'Shang-Chi', 
    recipientEmail: 'shangchi@tenrings.org', 
    recipientPhone: '555-0120', 
    recipientName: 'Katy Chen', 
    deliveryType: 'Online', 
    createdAt: new Date('2025-07-10T10:00:00'), 
    priority: 'rush', 
    status: 'completed', 
    handler: 'Michael Chen',
    deliveryDate: new Date('2025-07-11T09:00:00'), 
    addressLine1: 'San Francisco, CA', 
    specialMessage: 'Welcome to the circus.', 
    paymentMethod: 'Credit Card', 
    totalAmount: 130.00, 
    items: [{ name: 'Dragon Daisies', price: 130.00, quantity: 1, image: '/bouquet_square_5.jpeg' }] 
  }
];

export const useDemoOrderStore = create((set) => ({
  orders: initialOrders,

  addOrder: (newOrder) =>
    set((state) => ({
      orders: [newOrder, ...state.orders],
    })),

  updateStatus: (orderId, newStatus) =>
    set((state) => ({
      orders: state.orders.map((order) =>
        order._id === orderId ? { ...order, status: newStatus } : order
      ),
    })),
    
  getRandomHandler: () => handlers[Math.floor(Math.random() * handlers.length)],
  
  getRandomImage: () => productImages[Math.floor(Math.random() * productImages.length)]
}));